name: Build, Security Scan and Deploy Node.js project to Azure Function App - FunctionSilabo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  NODE_VERSION: "22.x"

jobs:
  # -------------------
  # 🧠 SAST - CodeQL Scan
  # -------------------
  codeql:
    name: SAST - CodeQL Analysis
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

  # -------------------
  # 🧰 Build Job
  # -------------------
  build:
    runs-on: ubuntu-latest
    needs: codeql
    permissions:
      contents: read

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        run: |
          cd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  # -------------------
  # ☁️ Deploy Job
  # -------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F0D3166D5ED64DD782DADA41290E5040 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5FED25D7EE6A42CF8A08E2AECC041D3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48C6DC1A3BEC4C6292A9376507903BCA }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "FunctionSilabo"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  # -------------------
  # 🔔 Notificaciones
  # -------------------
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_BACKEND }}
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: "🚀 Deploy FunctionSilabo"
          SLACK_MESSAGE: "El despliegue en Azure Functions se completó correctamente ✅"
          SLACK_COLOR: good

      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION_BACKEND }}
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: "❌ Error en Deploy FunctionSilabo"
          SLACK_MESSAGE: "El despliegue falló. Revisa los logs en GitHub Actions."
          SLACK_COLOR: danger
